create table lists (
       id int8 generated by default as identity,
        change_date timestamp not null,
        creation_date timestamp not null,
        title varchar(255) not null,
        primary key (id)
    )